### ISSUE TITLE
Timecop.freeze return wrong date

### ISSUE THREAD

**Issue by Sompatbu** [travisjeffery/timecop#208]
I've try to freeze the time to 14 July 2017 but Timecop.freeze return me the 13 July 2017 instead

Timecop.freeze(Date.parse("2017-07-14"))
 => 2017-07-13 17:00:00 +0000 

The machine I've running on now set the timezone to UTC but in the application.rb I've set the timezone to Bangkok +7. The gem version I've used is 0.9.1

Timecop should set the date/time to the input date/time without differentiate the timezone

**Comment by joshuacronemeyer** [comment]
These 2 times are equal, but I can see how you'd prefer to get the result with the specified timezone from application.rb. The thing is, #freeze without a block will return Time.now, which is just going to get you system time. Rails docs specify to use Time.current If you want the date with the timezone you've specified.

I'm not sure this is a bug, since timecop can work when acitve support isn't loaded and won't have access to the activesupport time extensions. It could be a nice enhancement to have it return Time.current instead of Time.now when active support is loaded.
