### ISSUE TITLE
9.x breaks this spec... why?

### ISSUE THREAD

**Issue by catmando** [travisjeffery/timecop#210]
This is probably my fault, but this spec worked in 8.x, but in 9.x broke:

```ruby
require 'spec_helper'

describe Timecop do

  before(:each) do
    Timecop.return
  end

  it 'new connections expire' do
    now = Time.now
    Timecop.travel(now+10)
    expect(Time.now).to be >= now+10
  end
end
```

**Comment by tom-lord** [comment]
Works fine for me; I cannot reproduce your problem.

The fact that you have this in your test:

    before(:each) do
      Timecop.return
    end

...Makes me suspect that the **real** cause of your problem is something else.

You should ideally be using `Timecop.travel`/`.freeze` in block form, to ensure that the time is always reset. Or if this is too inconvenient for your use case, any such test should include `Timecop.return` in an **`after`** block (or some other `ensure` block), to ensure it always gets run.
