### ISSUE TITLE
TimeCop handles timezones incorrectly

### ISSUE THREAD

**Issue by ssimeonov** [travisjeffery/timecop#41]
I am not sure why [this issue](https://github.com/jtrupiano/timecop/issues/8) was closed but I am following up with the suggestion to allow for handling of UTC dates. If this cannot happen by default, perhaps it can be done with an option of sorts.

In our case, the current logic leads to specs that pass during the day and fail during the night.

Here is an example:

``` ruby
it 'returns all reports generated on a certain date' do
    Timecop.freeze 1.day.ago do
      create_list :report, 4, name: '1.day.ago'
    end

    Report.generated_on(1.day.ago).count.should == 4
end
```

The intent of the spec couldn't be clearer. It is difficult for me to agree with any default logic in `Timecop` that leads to _inconsistent_ behavior in such a simple case.

**Comment by jamesmartin** [comment]
Our tests were failing on CI because our Rails 'config.time_zone' was configured to one thing, but the CI machine was configured to something different. Calling `Time.zone.now` returned the Rails configured timezone, but inside the `Timecop.freeze` block, the time was for the system timezone.

I was able to work around this problem by [changing the system timezone](https://gist.github.com/jamesmartin/a648b6ca27017c7d888b) of our CI machine.

**Comment by stratigos** [comment]
I believe I am experiencing these issues as well, currently trying to resolve issues regarding mixed use of `Date`, `Time`, and `ActiveSupport::TimeWithZone` first before submitting some code relating to timecop - however, I think there might be an issue between my local dev machine's system TZ and the TZ Timecop uses.

**Comment by maximveksler** [comment]
@stratigos i'm having a similar issue with ActiveSupport::TimeWithZone where it's converts to UTC but takes into the calculation the actual system timezone. So it gives me 2 different dates :(

So sad.

**Comment by IlkhamGaysin** [comment]
+1 I'm having an issue with differences time zones
My Rails application has set timezone: `Eastern Time (US & Canada)`
when I create record and pass to it mocked time the time zone of record set as `EDT` but time zone of mocked time is `GMT+3`. `GMT+3` is my time zone where I am it's Russia.

Rails 5.0.2
Ruby 2.3.1
Timecop 0.8.1

**Comment by ballcheck** [comment]
@IlkhamGaysin have you seen https://github.com/travisjeffery/timecop/issues/182 ?

**Comment by AndrewRayCode** [comment]
Still tracing an issue(?) with Timecop, my own notes:

```
> Timecop.freeze(Date.new(2000, 1, 1)) { puts Date.today.iso8601 }
=> "1999-12-31"
> Time.now.getlocal.zone
=> "PST"
> Time.now.gmt_offset
=> -28800
```
unsure if timezone is related here
```
bundle show timecop
/Users/me/.rvm/gems/ruby-2.3.4@project/gems/timecop-0.9.1
```

**Comment by dadamschi** [comment]
Hey, All!

I was reading through this (a bit, it's quite long!) via a co-worker and wanted to present a solution we have for this instance.

`Timecop.freeze(Time.parse('Tue Aug 28 06:00:00 CDT 2018').utc)`

We like this because it clear about your starting point for freezing. We want to be able to say "At this time in UTC relative to our local time (CDT), freeze time".

In an ideal world we can set the timezone from within the Timecop interface without having to get Rails involved. We don't do all of our work in Rails and keeping the two (Ruby, Rails) separate seems like a preferred position.

Hopefully this helps.
